local function preDistributionMerge()

	ProceduralDistributions.list.BandPracticeFridge = {
		rolls = 4,
		items = {
			"BeerBottle", 20,
			"BeerBottle", 10,
			"BeerCan", 20,
			"BeerCan", 10,
			"Burger", 8,
			"Burrito", 8,
			"CheeseSandwich", 4,
			"ChickenFried", 4,
			"Corndog", 4,
			"farming.MayonnaiseFull", 1,
			"FriedOnionRings", 8,
			"Fries", 8,
			"Gravy", 4,
			"Hotdog", 4,
			"Hotsauce", 1,
			"Ketchup", 1,
			"MuffinFruit", 4,
			"MuffinGeneric", 4,
			"Mustard", 1,
			"PeanutButterSandwich", 4,
			"Pop", 4,
			"Pop2", 4,
			"Pop3", 4,
			"PopBottle", 4,
			"Taco", 4,
			"BrazilianFood.Guarana", 4,
		}
	}

	ProceduralDistributions.list.BarCounterMisc = {
		rolls = 4,
		items = {
			"CardDeck", 6,
			"Cigarettes", 20,
			"Cigarettes", 10,
			"Corkscrew", 10,
			"Crisps", 10,
			"Dice", 6,
			"Lighter", 10,
			"Matches", 10,
			"Peanuts", 10,
			"Pickles", 6,
			"Pop", 10,
			"Pop2", 10,
			"Pop3", 10,
			"PopBottle", 6,
			"TortillaChips", 10,
			"BrazilianFood.Guarana", 10,
			"BrazilianFood.Fofura", 10,
		},
		junk = {	
			rolls = 1,
			items = {
				"DishCloth", 20,
			}
		}

	}

	ProceduralDistributions.list.CafeteriaDrinks = {
		rolls = 4,
		items = {
			"JuiceBox", 20,
			"JuiceBox", 10,
			"Pop", 8,
			"Pop2", 8,
			"Pop3", 8,
			"PopBottle", 8,
			"WaterBottleFull", 8,
			"WaterBottleFull", 8,
			"BrazilianFood.Guarana", 8,
		}
	}

	ProceduralDistributions.list.ClassroomDesk = {
		rolls = 4,
		items = {
			"BluePen", 8,
			"Book", 10,
			"Bracelet_LeftFriendshipTINT", 1,
			"Chocolate", 1,
			"ComicBook", 2,
			"Crisps", 1,
			"Cube", 4,
			"Eraser", 8,
			"Glue", 2,
			"Lollipop", 1,
			"Magazine", 2,
			"MagazineCrossword1", 2,
			"MagazineCrossword2", 2,
			"MagazineCrossword3", 2,
			"MagazineWordsearch1", 2,
			"MagazineWordsearch2", 2,
			"MagazineWordsearch3", 2,
			"Notebook", 10,
			"Pen", 8,
			"Pencil", 10,
			"Pop", 1,
			"Radio.CDplayer", 1,
			"RedPen", 8,
			"Scissors", 2,
			"Scotchtape", 4,
			"SheetPaper2", 20,
			"SheetPaper2", 10,
			"VideoGame", 1,
			"Yoyo", 4,
			"BrazilianFood.Guarana", 1,
			"BrazilianFood.Fofura", 1,
		}
	}

	ProceduralDistributions.list.CrateSodaCans = {
		rolls = 4,
		items = {
			"Pop", 20,
			"Pop", 10,
			"Pop2", 20,
			"Pop2", 10,
			"Pop3", 20,
			"Pop3", 10,
			"BrazilianFood.Guarana", 20,
			"BrazilianFood.Guarana", 10,
		}
	}

	ProceduralDistributions.list.FridgeBreakRoom = {
		rolls = 4,
		items = {
			"Apple", 8,
			"Banana", 8,
			"Burger", 4,
			"CakeSlice", 4,
			"farming.MayonnaiseFull", 1,
			"farming.RemouladeFull", 1,
			"Grapefruit", 8,
			"Hotdog", 4,
			"Ketchup", 1,
			"Lunchbag", 10,
			"Lunchbox", 10,
			"Lunchbox2", 0.001,
			"Mustard", 1,
			"Orange", 8,
			"Paperbag_Jays", 0.5,
			"Paperbag_Spiffos", 0.5,
			"Peach", 8,
			"Pear", 8,
			"Pie", 4,
			"PieApple", 4,
			"PieBlueberry", 4,
			"PieKeyLime", 4,
			"PieLemonMeringue", 4,
			"PiePumpkin", 4,
			"Pop", 4,
			"Pop2", 4,
			"Pop3", 4,
			"PopBottle", 4,
			"Processedcheese", 8,
			"WaterBottleFull", 4,
			"Yoghurt", 4,
			"Yoghurt", 4,
			"BrazilianFood.Guarana", 4,
		}
	}

	ProceduralDistributions.list.FridgeOffice = {
		rolls = 4,
		items = {
			"Apple", 8,
			"Banana", 8,
			"Burger", 4,
			"CakeSlice", 4,
			"Hotdog", 4,
			"Lunchbag", 10,
			"Lunchbox", 10,
			"Lunchbox2", 0.001,
			"Orange", 8,
			"Peach", 8,
			"Pie", 4,
			"PieApple", 4,
			"PieBlueberry", 4,
			"PieKeyLime", 4,
			"PieLemonMeringue", 4,
			"PiePumpkin", 4,
			"Pop", 4,
			"Pop2", 4,
			"Pop3", 4,
			"Pizza", 4,
			"PopBottle", 4,
			"WaterBottleFull", 4,
			"Yoghurt", 4,
			"BrazilianFood.Guarana", 4,
		}
	}

	ProceduralDistributions.list.FridgeSoda = {
		rolls = 4,
		items = {
			"Pop", 20,
			"Pop", 10,
			"Pop2", 20,
			"Pop2", 10,
			"Pop3", 20,
			"Pop3", 10,
			"PopBottle", 20,
			"PopBottle", 10,
			"BrazilianFood.Guarana", 20,
			"BrazilianFood.Guarana", 10,
		}
	}

	ProceduralDistributions.list.FridgeTrailerPark = {
		rolls = 4,
		items = {
			"Apple", 2,
			"Baloney", 1,
			"Banana", 2,
			"BeerCan", 4,
			"Butter", 4,
			"Carrots", 2,
			"Chicken", 0.5,
			"Corn", 2,
			"EggCarton", 0.8,
			"farming.Bacon", 1,
			"farming.MayonnaiseFull", 0.20,
			"farming.Strewberrie", 2,
			"farming.Tomato", 2,
			"Grapefruit", 2,
			"Grapes", 2,
			"Ham", 1,
			"Hotsauce", 0.20,
			"JuiceBox", 1,
			"Ketchup", 0.20,
			"Lard", 2,
			"Lemon", 2,
			"Lime", 2,
			"MapleSyrup", 0.20,
			"Margarine", 4,
			"MeatPatty", 0.8,
			"Milk", 4,
			"MincedMeat", 0.8,
			"Mustard", 0.20,
			"Onion", 2,
			"Orange", 2,
			"Paperbag_Jays", 0.2,
			"Paperbag_Spiffos", 0.2,
			"Pickles", 6,
			"Pop", 2,
			"Pop2", 2,
			"Pop3", 2,
			"PopBottle", 2,
			"PorkChop", 1,
			"Processedcheese", 6,
			"Salami", 1,
			"Sausage", 1,
			"Soysauce", 0.1,
			"Steak", 0.1,
			"WaterBottleFull", 1,
			"Yoghurt", 0.5,
			"BrazilianFood.Guarana", 2,
		}
	}

	ProceduralDistributions.list.GasStorageCombo = {
		rolls = 4,
		items = {
			"BeefJerky", 8,
			"CandyPackage", 4,
			"ChocoCakes", 8,
			"Chocolate", 10,
			"Cigarettes", 10,
			"Cigarettes", 20,
			"Crisps", 10,
			"Crisps2", 10,
			"Crisps3", 10,
			"Crisps4", 10,
			"DehydratedMeatStick", 10,
			"GranolaBar", 8,
			"Gum", 10,
			"GummyBears", 10,
			"GummyWorms", 10,
			"HiHis", 8,
			"JellyBeans", 10,
			"Jujubes", 10,
			"LicoriceBlack", 4,
			"LicoriceRed", 10,
			"Lighter", 10,
			"Matches", 10,
			"Peanuts", 6,
			"Plonkies", 8,
			"Pop", 10,
			"Pop2", 10,
			"Pop3", 10,
			"PopBottle", 10,
			"QuaggaCakes", 8,
			"SnoGlobes", 8,
			"SunflowerSeeds", 6,
			"TortillaChips", 10,
			"WaterBottleFull", 10,
			"BrazilianFood.Guarana", 10,
			"BrazilianFood.Fofura", 10,
		}
	}

	ProceduralDistributions.list.GigamartBottles = {
		rolls = 4,
		items = {
			"WaterBottleFull", 20,
			"WaterBottleFull", 10,
			"PopBottle", 20,
			"PopBottle", 10,
			"Pop", 20,
			"Pop", 10,
			"Pop2", 20,
			"Pop2", 10,
			"Pop3", 20,
			"Pop3", 10,
			"BrazilianFood.Guarana", 20,
			"BrazilianFood.Guarana", 10,
		}
	}

	ProceduralDistributions.list.KitchenBottles = {
		rolls = 4,
		items = {
			"BeerBottle", 1,
			"BeerCan", 2,
			"Corkscrew", 4,
			"DishCloth", 10,
			"JuiceBox", 6,
			"PlasticCup", 10,
			"Pop", 10,
			"Pop2", 10,
			"Pop3", 10,
			"PopBottle", 8,
			"PopBottle", 8,
			"WaterBottleFull", 8,
			"WaterBottleFull", 8,
			"WhiskeyFull", 2,
			"Wine", 1,
			"Wine2", 1,
			"BrazilianFood.Guarana", 10,
		}
	}

	ProceduralDistributions.list.MotelFridge = {
		rolls = 1,
		items = {
			"Burger", 6,
			"Burrito", 10,
			"Corndog", 10,
			"Fries", 6,
			"Hotdog", 6,
			"MuffinFruit", 10,
			"MuffinGeneric", 10,
			"Pizza", 6,
			"Pop", 6,
			"Pop2", 6,
			"Pop3", 6,
			"PopBottle", 6,
			"PopBottle", 6,
			"WhiskeyFull", 2,
			"BrazilianFood.Guarana", 6,
		}
	}

	ProceduralDistributions.list.StoreShelfCombo = {
		rolls = 4,
		items = {
			"BeefJerky", 8,
			"CandyPackage", 4,
			"ChocoCakes", 8,
			"Chocolate", 10,
			"Crisps", 10,
			"Crisps2", 10,
			"Crisps3", 10,
			"Crisps4", 10,
			"DehydratedMeatStick", 10,
			"GranolaBar", 8,
			"Gum", 10,
			"GummyBears", 10,
			"GummyWorms", 10,
			"HiHis", 8,
			"JellyBeans", 10,
			"Jujubes", 10,
			"LicoriceBlack", 4,
			"LicoriceRed", 10,
			"Peanuts", 6,
			"Plonkies", 8,
			"Pop", 10,
			"Pop2", 10,
			"Pop3", 10,
			"PopBottle", 10,
			"PopBottle", 20,
			"QuaggaCakes", 8,
			"SnoGlobes", 8,
			"SunflowerSeeds", 6,
			"TortillaChips", 10,
			"WaterBottleFull", 10,
			"BrazilianFood.Guarana", 10,
			"BrazilianFood.Fofura", 10,
		}
	}

	ProceduralDistributions.list.StoreShelfDrinks = {
		rolls = 4,
		items = {
			"Pop", 20,
			"Pop", 10,
			"Pop2", 20,
			"Pop2", 10,
			"Pop3", 20,
			"Pop3", 10,
			"PopBottle", 20,
			"PopBottle", 10,
			"WaterBottleFull", 20,
			"WaterBottleFull", 10,
			"BrazilianFood.Guarana", 20,
			"BrazilianFood.Guarana", 10,
		}
	}

	ProceduralDistributions.list.TheatreDrinks = {
		rolls = 4,
		items = {
			"Pop", 20,
			"Pop", 10,
			"Pop2", 20,
			"Pop2", 10,
			"Pop3", 20,
			"Pop3", 10,
			"PopBottle", 20,
			"PopBottle", 20,
			"PopBottle", 10,
			"PopBottle", 10,
			"BrazilianFood.Guarana", 20,
			"BrazilianFood.Guarana", 10,
		}
	}

	ProceduralDistributions.list.FreezerGeneric = {
		rolls = 4,
		items = {
			"Chicken", 6,
			"CornFrozen", 10,
			"farming.Bacon", 6,
			"Ham", 6,
			"Icecream", 10,
			"IcePick", 0.1,
			"MeatPatty", 8,
			"MincedMeat", 8,
			"MixedVegetables", 10,
			"MuttonChop", 2,
			"Oysters", 2,
			"Peas", 10,
			"PorkChop", 8,
			"Salmon", 4,
			"Sausage", 8,
			"Shrimp", 2,
			"Steak", 6,
			"BrazilianFood.Acai", 10,
		}
	}

	ProceduralDistributions.list.FreezerRich = {
		rolls = 4,
		items = {
			"Chicken", 6,
			"CornFrozen", 10,
			"farming.Bacon", 6,
			"Ham", 6,
			"Icecream", 10,
			"IcePick", 0.1,
			"MeatPatty", 4,
			"MincedMeat", 4,
			"MixedVegetables", 10,
			"MuttonChop", 8,
			"Oysters", 8,
			"Peas", 10,
			"PizzaRecipe", 0.1,
			"PizzaWhole", 0.1,
			"PorkChop", 4,
			"Salmon", 8,
			"Sausage", 4,
			"Shrimp", 8,
			"Steak", 8,
			"BrazilianFood.Acai", 10,
		}
	}

	ProceduralDistributions.list.FreezerTrailerPark = {
		rolls = 4,
		items = {
			"Chicken", 6,
			"CornFrozen", 10,
			"farming.Bacon", 6,
			"Ham", 6,
			"Icecream", 10,
			"IcePick", 0.1,
			"MeatPatty", 8,
			"MincedMeat", 8,
			"MixedVegetables", 10,
			"Peas", 10,
			"PorkChop", 8,
			"Sausage", 8,
			"Steak", 2,
			"BrazilianFood.Acai", 10,
		}
	}

	ProceduralDistributions.list.FreezerIceCream = {
		rolls = 4,
		items = {
			"Icecream", 50,
			"Icecream", 20,
			"Icecream", 20,
			"Icecream", 10,
			"Icecream", 10,
			"BrazilianFood.Acai", 50,
			"BrazilianFood.Acai", 20,
			"BrazilianFood.Acai", 20,
			"BrazilianFood.Acai", 10,
			"BrazilianFood.Acai", 10,
		}
	}

	ProceduralDistributions.list.TheatreKitchenFreezer = {
		rolls = 4,
		items = {
			"Icecream", 50,
			"Icecream", 20,
			"Icecream", 20,
			"Icecream", 10,
			"Icecream", 10,
			"BrazilianFood.Acai", 50,
			"BrazilianFood.Acai", 20,
			"BrazilianFood.Acai", 20,
			"BrazilianFood.Acai", 10,
			"BrazilianFood.Acai", 10,
		}
	}

	ProceduralDistributions.list.CafeteriaSnacks = {
		rolls = 4,
		items = {
			"CakeSlice", 8,
			"Chocolate", 10,
			"Chocolate", 10,
			"CinnamonRoll", 4,
			"CookieChocolateChip", 4,
			"CookieJelly", 4,
			"CookiesChocolate", 4,
			"CookiesOatmeal", 4,
			"CookiesShortbread", 4,
			"CookiesSugar", 4,
			"Crisps", 8,
			"Crisps2", 8,
			"Crisps3", 8,
			"Crisps4", 8,
			"Cupcake", 4,
			"MuffinFruit", 8,
			"MuffinGeneric", 8,
			"Painauchocolat", 4,
			"Pie", 4,
			"PieApple", 4,
			"PieBlueberry", 4,
			"PieKeyLime", 4,
			"PieLemonMeringue", 4,
			"PiePumpkin", 4,
			"PiePumpkin", 4,
			"BrazilianFood.Fofura", 8,
		}
	}

	ProceduralDistributions.list.CrateChips = {
		rolls = 4,
		items = {
			"Crisps", 20,
			"Crisps", 10,
			"Crisps2", 20,
			"Crisps2", 10,
			"Crisps3", 20,
			"Crisps3", 10,
			"Crisps4", 20,
			"Crisps4", 10,
			"BrazilianFood.Fofura", 20,
			"BrazilianFood.Fofura", 10,
		}
	}

	ProceduralDistributions.list.GigamartCrisps = {
		rolls = 4,
		items = {
			"Crisps", 20,
			"Crisps", 10,
			"Crisps2", 20,
			"Crisps2", 10,
			"Crisps3", 20,
			"Crisps3", 10,
			"Crisps4", 20,
			"Crisps4", 10,
			"TortillaChips", 10,
			"Peanuts", 10,
			"Popcorn", 10,
			"SunflowerSeeds", 10,
			"BrazilianFood.Fofura", 20,
			"BrazilianFood.Fofura", 10,
		}
	}

	ProceduralDistributions.list.GroceryStorageCrate1 = {
		rolls = 4,
		items = {
			"BouillonCube", 1,
			"Candycane", 1,
			"CandyFruitSlices", 1,
			"CandyPackage", 1,
			"CannedBolognese", 1,
			"CannedCarrots2", 0.8,
			"CannedChili", 1,
			"CannedCorn", 0.8,
			"CannedCornedBeef", 1,
			"CannedFruitCocktail", 1,
			"CannedMilk", 0.4,
			"CannedMushroomSoup", 1,
			"CannedPeaches", 0.8,
			"CannedPeas", 0.8,
			"CannedPineapple", 0.8,
			"CannedPotato2", 0.8,
			"CannedSardines", 1,
			"CannedTomato2", 0.8,
			"Cereal", 1,
			"Chocolate", 1,
			"ChocolateCoveredCoffeeBeans", 1,
			"Coffee2", 1,
			"Crackers", 1,
			"Crisps", 1,
			"Crisps2", 1,
			"Crisps3", 1,
			"Crisps4", 1,
			"DriedBlackBeans", 0.8,
			"DriedChickpeas", 0.8,
			"DriedKidneyBeans", 0.8,
			"DriedLentils", 0.8,
			"DriedSplitPeas", 0.8,
			"DriedWhiteBeans", 0.8,
			"GranolaBar", 1,
			"Gum", 1,
			"GummyBears", 1,
			"GummyWorms", 1,
			"HardCandies", 1,
			"JellyBeans", 1,
			"Jujubes", 1,
			"LicoriceBlack", 1,
			"LicoriceRed", 1,
			"Macandcheese", 1,
			"MintCandy", 1,
			"Modjeska", 1,
			"Pasta", 1,
			"Peanuts", 1,
			"Peppermint", 1,
			"Popcorn", 1,
			"Ramen", 1,
			"Rice", 1,
			"RockCandy", 1,
			"SackProduce_Apple", 0.1,
			"SackProduce_BellPepper", 0.1,
			"SackProduce_Broccoli", 0.1,
			"SackProduce_Cabbage", 0.1,
			"SackProduce_Carrot", 0.1,
			"SackProduce_Cherry", 0.1,
			"SackProduce_Corn", 0.1,
			"SackProduce_Eggplant", 0.1,
			"SackProduce_Leek", 0.1,
			"SackProduce_Lettuce", 0.1,
			"SackProduce_Onion", 0.1,
			"SackProduce_Peach", 0.1,
			"SackProduce_Pear", 0.1,
			"SackProduce_Potato", 0.1,
			"SackProduce_RedRadish", 0.1,
			"SackProduce_Strawberry", 0.1,
			"SackProduce_Tomato", 0.1,
			"SunflowerSeeds", 1,
			"TacoShell", 1,
			"Teabag2", 1,
			"TinnedBeans", 1,
			"TinnedSoup", 1,
			"TortillaChips", 1,
			"TunaTin", 1,
			"TVDinner", 1,
			"BrazilianFood.Fofura", 1,
		}
	}

	ProceduralDistributions.list.KitchenDryFood = {
		rolls = 4,
		items = {
			"BeefJerky", 6,
			"BouillonCube", 10,
			"Cereal", 10,
			"Chocolate", 6,
			"Crackers", 10,
			"Crisps", 4,
			"Crisps2", 4,
			"Crisps3", 4,
			"Crisps4", 4,
			"DishCloth", 10,
			"DriedBlackBeans", 5,
			"DriedChickpeas", 5,
			"DriedKidneyBeans", 5,
			"DriedLentils", 5,
			"DriedSplitPeas", 5,
			"DriedWhiteBeans", 5,
			"Macandcheese", 10,
			"Marinara", 10,
			"Pasta", 10,
			"Pepper", 8,
			"Popcorn", 8,
			"Ramen", 6,
			"Rice", 4,
			"Salt", 8,
			"TacoShell", 2,
			"TortillaChips", 4,
			"TVDinner", 4,
			"BrazilianFood.Fofura", 4,
		},
		junk = {	
			rolls = 1,
			items = {
				"DeadMouse", 1,
				"DeadRat", 1,
			}
		}

	}

	ProceduralDistributions.list.PrisonCellRandom = {
		rolls = 4,
		items = {
			"Antibiotics", 0.20,
			"Bandage", 0.20,
			"BorisBadger", 0.001,
			"Bowl", 10,
			"ButterKnife", 0.05,
			"Cereal", 4,
			"Chocolate", 4,
			"Cigarettes", 8,
			"Comb", 4,
			"CordlessPhone", 0.01,
			"Crayons", 8,
			"Crisps", 10,
			"CuttingBoardPlastic", 0.01,
			"CuttingBoardWooden", 0.01,
			"Doll", 4,
			"FluffyfootBunny", 0.001,
			"FreddyFox", 0.001,
			"FurbertSquirrel", 0.001,
			"HottieZ", 0.01,
			"JacquesBeaver", 0.001,
			"KitchenKnife", 0.01,
			"Lighter", 4,
			"Magazine", 10,
			"MagazineCrossword1", 2,
			"MagazineCrossword2", 2,
			"MagazineCrossword3", 2,
			"MagazineWordsearch1", 2,
			"MagazineWordsearch2", 2,
			"MagazineWordsearch3", 2,
			"Matches", 8,
			"Mirror", 8,
			"MoleyMole", 0.001,
			"Mugl", 4,
			"MugRed", 4,
			"MugWhite", 4,
			"Newspaper", 10,
			"Notebook", 10,
			"PancakeHedgehog", 0.001,
			"Pencil", 10,
			"Pills", 0.5,
			"Radio.CDplayer", 1,
			"Radio.RadioBlack", 1,
			"Ramen", 10,
			"SheetPaper2", 10,
			"Shoes_FlipFlop", 6,
			"Soap2", 10,
			"Socks_Ankle", 4,
			"Spiffo", 0.001,
			"Spoon", 20,
			"Teabag2", 6,
			"Toothbrush", 10,
			"Toothpaste", 10,
			"ToyBear", 4,
			"TunaTin", 4,
			"WhiskeyFull", 0.01,
			"BrazilianFood.Fofura", 10,
		},
		junk = {	
			rolls = 1,
			items = {
				"BathTowel", 20,
				"Boilersuit_Prisoner", 100,
			}
		}

	}

	ProceduralDistributions.list.StoreShelfSnacks = {
		rolls = 4,
		items = {
			"BeefJerky", 8,
			"CandyPackage", 4,
			"ChocoCakes", 8,
			"Chocolate", 8,
			"Crisps", 10,
			"Crisps2", 10,
			"Crisps3", 10,
			"Crisps4", 10,
			"DehydratedMeatStick", 10,
			"GranolaBar", 8,
			"Gum", 10,
			"GummyBears", 10,
			"GummyWorms", 10,
			"HiHis", 8,
			"JellyBeans", 10,
			"Jujubes", 10,
			"LicoriceBlack", 4,
			"LicoriceRed", 10,
			"Peanuts", 6,
			"Plonkies", 8,
			"QuaggaCakes", 8,
			"SnoGlobes", 8,
			"SunflowerSeeds", 6,
			"TortillaChips", 10,
			"BrazilianFood.Fofura", 10,
		}
	}

	ProceduralDistributions.list.BakeryKitchenBaking = {
		rolls = 4,
		items = {
			"Aluminum", 8,
			"BakingSoda", 10,
			"BreadKnife", 6,
			"CannedMilk", 4,
			"ChocolateChips", 10,
			"CocoaPowder", 10,
			"Flour", 10,
			"Flour", 20,
			"OilVegetable", 10,
			"RollingPin", 8,
			"Sugar", 10,
			"SugarBrown", 10,
			"Yeast", 10,
			"BrazilianFood.FarinhaTapioca", 10,
			"BrazilianFood.FarinhaTapioca", 20,
		},
		junk = {	
			rolls = 1,
			items = {
				"Apron_White", 20,
				"DishCloth", 20,
			}
		}

	}

	ProceduralDistributions.list.ChineseKitchenBaking = {
		rolls = 4,
		items = {
			"Aluminum", 8,
			"BreadKnife", 8,
			"Flour", 20,
			"Flour", 10,
			"OilVegetable", 10,
			"Rice", 20,
			"Rice", 10,
			"RollingPin", 8,
			"Yeast", 10,
			"BrazilianFood.FarinhaTapioca", 20,
			"BrazilianFood.FarinhaTapioca", 10,
		},
		junk = {	
			rolls = 1,
			items = {
				"Apron_White", 20,
				"DishCloth", 20,
			}
		}

	}

	ProceduralDistributions.list.CrateFlour = {
		rolls = 4,
		items = {
			"Flour", 50,
			"Flour", 20,
			"Flour", 20,
			"Flour", 10,
			"Flour", 10,
			"BrazilianFood.FarinhaTapioca", 50,
			"BrazilianFood.FarinhaTapioca", 20,
			"BrazilianFood.FarinhaTapioca", 20,
			"BrazilianFood.FarinhaTapioca", 10,
			"BrazilianFood.FarinhaTapioca", 10,
		}
	}

	ProceduralDistributions.list.GigamartBakingMisc = {
		rolls = 4,
		items = {
			"Aluminum", 20,
			"Aluminum", 10,
			"BakingSoda", 10,
			"CannedMilk", 4,
			"ChocolateChips", 10,
			"CocoaPowder", 10,
			"Flour", 20,
			"Flour", 10,
			"OatsRaw", 10,
			"OilOlive", 10,
			"OilVegetable", 10,
			"Sugar", 10,
			"SugarBrown", 10,
			"Yeast", 10,
			"BrazilianFood.FarinhaTapioca", 20,
			"BrazilianFood.FarinhaTapioca", 10,
		}
	}

	ProceduralDistributions.list.ItalianKitchenBaking = {
		rolls = 4,
		items = {
			"Aluminum", 8,
			"BreadKnife", 8,
			"DriedBlackBeans", 5,
			"DriedChickpeas", 5,
			"DriedKidneyBeans", 5,
			"DriedLentils", 5,
			"DriedSplitPeas", 5,
			"DriedWhiteBeans", 5,
			"Flour", 10,
			"Flour", 20,
			"OilOlive", 10,
			"OilOlive", 20,
			"Pasta", 10,
			"Pasta", 20,
			"RollingPin", 8,
			"Yeast", 10,
			"BrazilianFood.FarinhaTapioca", 10,
			"BrazilianFood.FarinhaTapioca", 20,
		},
		junk = {	
			rolls = 1,
			items = {
				"Apron_White", 20,
				"DishCloth", 20,
			}
		}

	}

	ProceduralDistributions.list.JaysKitchenBaking = {
		rolls = 4,
		items = {
			"Aluminum", 8,
			"BakingSoda", 10,
			"BreadKnife", 8,
			"Cornflour", 20,
			"Cornflour", 10,
			"Flour", 20,
			"Flour", 10,
			"OilVegetable", 20,
			"OilVegetable", 10,
			"RollingPin", 8,
			"Sugar", 10,
			"Yeast", 10,
			"BrazilianFood.FarinhaTapioca", 20,
			"BrazilianFood.FarinhaTapioca", 10,
		},
		junk = {	
			rolls = 1,
			items = {
				"Apron_White", 20,
				"DishCloth", 20,
			}
		}

	}

	ProceduralDistributions.list.KitchenBaking = {
		rolls = 4,
		items = {
			"Aluminum", 8,
			"BakingSoda", 6,
			"CannedMilk", 4,
			"Chocolate", 8,
			"ChocolateChips", 6,
			"CocoaPowder", 6,
			"Cornflour", 2,
			"Flour", 10,
			"GrahamCrackers", 6,
			"GravyMix", 2,
			"Marshmallows", 6,
			"OilOlive", 4,
			"OilVegetable", 6,
			"PancakeMix", 8,
			"Sugar", 6,
			"SugarBrown", 6,
			"Yeast", 4,
			"BrazilianFood.FarinhaTapioca", 10,
		},
		junk = {	
			rolls = 1,
			items = {
				"DeadMouse", 1,
				"DeadRat", 1,
			}
		}

	}

	ProceduralDistributions.list.PizzaKitchenBaking = {
		rolls = 4,
		items = {
			"Aluminum", 8,
			"BakingTray", 10,
			"BakingTray", 20,
			"BreadKnife", 8,
			"Flour", 10,
			"Flour", 20,
			"OilOlive", 10,
			"PizzaRecipe", 10,
			"RollingPin", 8,
			"Yeast", 10,
			"BrazilianFood.FarinhaTapioca", 10,
			"BrazilianFood.FarinhaTapioca", 20,
		},
		junk = {	
			rolls = 1,
			items = {
				"Apron_White", 20,
				"DishCloth", 20,
			}
		}

	}

	ProceduralDistributions.list.StoreKitchenBaking = {
		rolls = 4,
		items = {
			"Aluminum", 8,
			"BakingPan", 10,
			"BakingSoda", 10,
			"BakingTray", 10,
			"CannedMilk", 4,
			"Flour", 10,
			"Flour", 20,
			"MuffinTray", 10,
			"OilOlive", 10,
			"OilVegetable", 10,
			"RollingPin", 8,
			"Sugar", 10,
			"Yeast", 10,
			"BrazilianFood.FarinhaTapioca", 10,
			"BrazilianFood.FarinhaTapioca", 20,
		},
		junk = {	
			rolls = 1,
			items = {
				"Apron_White", 20,
				"DishCloth", 20,
			}
		}

	}

	ProceduralDistributions.list.WesternKitchenBaking = {
		rolls = 4,
		items = {
			"Aluminum", 8,
			"BakingSoda", 10,
			"BreadKnife", 8,
			"Cornflour", 20,
			"Cornflour", 10,
			"Flour", 20,
			"Flour", 10,
			"OilVegetable", 10,
			"RollingPin", 8,
			"Sugar", 10,
			"Yeast", 10,
			"BrazilianFood.FarinhaTapioca", 20,
			"BrazilianFood.FarinhaTapioca", 10,
		},
		junk = {	
			rolls = 1,
			items = {
				"Apron_White", 20,
				"DishCloth", 20,
			}
		}

	}

	SuburbsDistributions.all.vendingpop = {
		rolls = 4,
		items = {
			"Pop", 10,
			"Pop2", 10,
			"Pop3", 10,
			"PopBottle", 10,
			"BrazilianFood.Guarana", 10,
		}
	}

	SuburbsDistributions.Bag_Schoolbag = {
		rolls = 1,
		items = {
			"BluePen", 8,
			"Book", 10,
			"Book", 20,
			"Chocolate", 1,
			"ComicBook", 10,
			"Crisps", 1,
			"Disc_Retail", 2,
			"Earbuds", 1,
			"GranolaBar", 1,
			"Lighter", 1,
			"Pen", 8,
			"Pencil", 10,
			"Pop", 1,
			"Radio.CDplayer", 1,
			"RedPen", 8,
			"RubberBand", 1,
			"Scissors", 2,
			"SunflowerSeeds", 1,
			"BrazilianFood.Guarana", 1,
			"BrazilianFood.Fofura", 1,
		}
	}

	SuburbsDistributions.GroceryBag1 = {
		rolls = 1,
		items = {
			"Apple", 2,
			"Avocado", 1,
			"BakingSoda", 1,
			"Baloney", 0.8,
			"Banana", 2,
			"BellPepper", 1,
			"BouillonCube", 1,
			"Broccoli", 2,
			"Butter", 2,
			"Candycane", 1,
			"CandyPackage", 1,
			"CannedBolognese", 1,
			"CannedCarrots2", 0.8,
			"CannedChili", 1,
			"CannedCorn", 0.8,
			"CannedCornedBeef", 1,
			"CannedFruitCocktail", 1,
			"CannedMushroomSoup", 1,
			"CannedPeaches", 0.8,
			"CannedPeas", 0.8,
			"CannedPineapple", 0.8,
			"CannedPotato2", 0.8,
			"CannedSardines", 1,
			"CannedTomato2", 0.8,
			"Carrots", 2,
			"Cereal", 1,
			"Cheese", 2,
			"Cherry", 2,
			"Chicken", 0.8,
			"Chocolate", 1,
			"ChocolateChips", 1,
			"ChocolateCoveredCoffeeBeans", 1,
			"CocoaPowder", 1,
			"Coffee2", 1,
			"Corn", 2,
			"Crackers", 1,
			"Crisps", 1,
			"Crisps2", 1,
			"Crisps3", 1,
			"Crisps4", 1,
			"DriedBlackBeans", 0.8,
			"DriedChickpeas", 0.8,
			"DriedKidneyBeans", 0.8,
			"DriedLentils", 0.8,
			"DriedSplitPeas", 0.8,
			"DriedWhiteBeans", 0.8,
			"EggCarton", 0.8,
			"Eggplant", 2,
			"farming.Bacon", 0.8,
			"farming.Cabbage", 2,
			"farming.MayonnaiseFull", 0.25,
			"farming.RedRadish", 2,
			"farming.RemouladeFull", 0.25,
			"farming.Strewberrie", 2,
			"farming.Tomato", 2,
			"Flour", 1,
			"GranolaBar", 1,
			"Grapefruit", 2,
			"Grapes", 2,
			"Gum", 1,
			"GummyBears", 1,
			"GummyWorms", 1,
			"Ham", 0.8,
			"HardCandies", 1,
			"Hotsauce", 0.25,
			"JellyBeans", 1,
			"JuiceBox", 1,
			"Jujubes", 1,
			"Ketchup", 0.25,
			"Lard", 1,
			"Leek", 2,
			"Lemon", 2,
			"Lettuce", 2,
			"LicoriceBlack", 1,
			"LicoriceRed", 1,
			"Lime", 2,
			"Macandcheese", 1,
			"MapleSyrup", 0.25,
			"Margarine", 2,
			"MeatPatty", 0.8,
			"Milk", 4,
			"MincedMeat", 0.8,
			"MintCandy", 1,
			"Modjeska", 1,
			"Mustard", 0.25,
			"MuttonChop", 0.5,
			"OatsRaw", 1,
			"OilOlive", 1,
			"OilVegetable", 1,
			"Onion", 2,
			"Orange", 2,
			"Pasta", 1,
			"Peach", 2,
			"Peanuts", 1,
			"Pear", 2,
			"PepperJalapeno", 1,
			"Peppermint", 1,
			"Pickles", 6,
			"Pineapple", 1,
			"Pop", 4,
			"Pop2", 4,
			"Pop3", 4,
			"PopBottle", 2,
			"Popcorn", 1,
			"PorkChop", 0.8,
			"Processedcheese", 6,
			"Ramen", 1,
			"Rice", 1,
			"RockCandy", 1,
			"Salami", 0.8,
			"Salmon", 0.5,
			"Sausage", 0.8,
			"Soysauce", 0.25,
			"Steak", 0.5,
			"Sugar", 1,
			"SugarBrown", 1,
			"SunflowerSeeds", 1,
			"TacoShell", 1,
			"Teabag2", 1,
			"TinnedBeans", 1,
			"TinnedSoup", 1,
			"TortillaChips", 1,
			"TunaTin", 1,
			"TVDinner", 1,
			"WaterBottleFull", 1,
			"Yeast", 1,
			"Yoghurt", 1,
			"Zucchini", 2,
			"BrazilianFood.Guarana", 4,
			"BrazilianFood.Fofura", 1,
			"BrazilianFood.FarinhaTapioca", 1,
		}
	}

	SuburbsDistributions.GroceryBag3 = {
		rolls = 1,
		items = {
			"Candycane", 10,
			"CandyPackage", 10,
			"CannedBolognese", 10,
			"CannedChili", 10,
			"CannedFruitCocktail", 10,
			"CannedMushroomSoup", 10,
			"Chocolate", 20,
			"ChocolateCoveredCoffeeBeans", 10,
			"Crisps", 10,
			"Crisps2", 10,
			"Crisps3", 10,
			"Crisps4", 10,
			"GranolaBar", 20,
			"Gum", 20,
			"GummyBears", 10,
			"GummyWorms", 10,
			"HardCandies", 10,
			"JellyBeans", 10,
			"Jujubes", 10,
			"LicoriceBlack", 10,
			"LicoriceRed", 10,
			"MintCandy", 10,
			"Modjeska", 10,
			"Peppermint", 10,
			"Pop", 10,
			"Pop2", 10,
			"Pop3", 10,
			"PopBottle", 10,
			"Popcorn", 10,
			"RockCandy", 10,
			"SunflowerSeeds", 10,
			"TinnedBeans", 10,
			"TinnedSoup", 10,
			"TortillaChips", 10,
			"TVDinner", 10,
			"BrazilianFood.Guarana", 10,
			"BrazilianFood.Fofura", 10,
		}
	}

	SuburbsDistributions.GroceryBag5 = {
		rolls = 1,
		items = {
			"Crisps", 50,
			"Crisps", 10,
			"Crisps2", 50,
			"Crisps2", 10,
			"Crisps3", 50,
			"Crisps3", 10,
			"Crisps4", 50,
			"Crisps4", 10,
			"farming.Bacon", 20,
			"farming.MayonnaiseFull", 20,
			"farming.Tomato", 20,
			"Ketchup", 50,
			"Lettuce", 20,
			"MincedMeat", 100,
			"MincedMeat", 100,
			"MincedMeat", 50,
			"MincedMeat", 50,
			"Mustard", 50,
			"Onion", 20,
			"Pickles", 20,
			"Pop", 50,
			"Pop", 10,
			"Pop2", 50,
			"Pop2", 10,
			"Pop3", 50,
			"Pop3", 10,
			"PopBottle", 50,
			"PopBottle", 10,
			"Processedcheese", 50,
			"Processedcheese", 10,
			"Steak", 50,
			"Steak", 50,
			"Steak", 20,
			"Steak", 20,
			"TortillaChips", 50,
			"TortillaChips", 10,
			"BrazilianFood.Guarana", 50,
			"BrazilianFood.Guarana", 10,
			"BrazilianFood.Fofura", 50,
			"BrazilianFood.Fofura", 10,
		}
	}

	SuburbsDistributions.Bag_Satchel = {
		rolls = 1,
		items = {
			"BluePen", 8,
			"Book", 20,
			"Book", 10,
			"CheeseSandwich", 20,
			"Cigarettes", 4,
			"ComicBook", 10,
			"Crisps", 10,
			"Disc_Retail", 2,
			"Earbuds", 1,
			"Lighter", 1,
			"PeanutButterSandwich", 20,
			"Pen", 8,
			"Pencil", 10,
			"Pop", 1,
			"Radio.CDplayer", 1,
			"RedPen", 8,
			"RubberBand", 1,
			"Scissors", 2,
			"BrazilianFood.Guarana", 1,
			"BrazilianFood.Fofura", 10,
		}
	}

	SuburbsDistributions.all.vendingsnack = {
		rolls = 4,
		items = {
			"Crisps", 10,
			"Crisps2", 10,
			"Crisps3", 10,
			"BrazilianFood.Fofura", 10,
		}
	}

	SuburbsDistributions.Bag_ALICEpack = {
		rolls = 1,
		items = {
			"AlcoholWipes", 1,
			"Bandage", 1,
			"BathTowel", 2,
			"camping.CampingTentKit", 0.5,
			"Chocolate", 1,
			"Cigarettes", 1,
			"Crisps", 1,
			"Disc_Retail", 2,
			"Earbuds", 1,
			"GranolaBar", 1,
			"HoodieDOWN_WhiteTINT", 0.5,
			"Lighter", 1,
			"Peanuts", 1,
			"Radio.CDplayer", 1,
			"Socks_Ankle", 2,
			"SunflowerSeeds", 1,
			"Vest_DefaultTEXTURE_TINT", 2,
			"WaterBottleFull", 1,
			"BrazilianFood.Fofura", 1,
		}
	}

	SuburbsDistributions.Bag_BigHikingBag = {
		rolls = 1,
		items = {
			"AlcoholWipes", 1,
			"Bandage", 1,
			"BathTowel", 2,
			"camping.CampingTentKit", 0.5,
			"Chocolate", 1,
			"Cigarettes", 1,
			"Crisps", 1,
			"Disc_Retail", 2,
			"Earbuds", 1,
			"GranolaBar", 1,
			"HoodieDOWN_WhiteTINT", 0.5,
			"Lighter", 1,
			"Peanuts", 1,
			"Radio.CDplayer", 1,
			"Socks_Ankle", 2,
			"SunflowerSeeds", 1,
			"Vest_DefaultTEXTURE_TINT", 2,
			"WaterBottleFull", 1,
			"BrazilianFood.Fofura", 1,
		}
	}

	SuburbsDistributions.Bag_FoodSnacks = {
		rolls = 2,
		items = {
			"BeefJerky", 20,
			"BeefJerky", 10,
			"ChocoCakes", 10,
			"Chocolate", 20,
			"Chocolate", 10,
			"Crisps", 10,
			"Crisps2", 10,
			"Crisps3", 10,
			"Crisps4", 10,
			"DehydratedMeatStick", 20,
			"DehydratedMeatStick", 10,
			"GranolaBar", 20,
			"GranolaBar", 10,
			"GummyBears", 10,
			"GummyWorms", 10,
			"HiHis", 10,
			"JellyBeans", 10,
			"Jujubes", 10,
			"LicoriceBlack", 10,
			"LicoriceRed", 10,
			"Peanuts", 10,
			"Plonkies", 10,
			"QuaggaCakes", 10,
			"SnoGlobes", 10,
			"SunflowerSeeds", 10,
			"TortillaChips", 10,
			"BrazilianFood.Fofura", 10,
		}
	}

	SuburbsDistributions.Bag_NormalHikingBag = {
		rolls = 1,
		items = {
			"AlcoholWipes", 1,
			"Bandage", 1,
			"BathTowel", 2,
			"Chocolate", 1,
			"Cigarettes", 1,
			"Crisps", 1,
			"Disc_Retail", 2,
			"Earbuds", 1,
			"GranolaBar", 1,
			"HoodieDOWN_WhiteTINT", 0.5,
			"Lighter", 1,
			"Peanuts", 1,
			"Radio.CDplayer", 1,
			"Socks_Ankle", 2,
			"SunflowerSeeds", 1,
			"Vest_DefaultTEXTURE_TINT", 2,
			"WaterBottleFull", 1,
			"BrazilianFood.Fofura", 1,
		}
	}

	SuburbsDistributions.Bag_SurvivorBag = {
		rolls = 2,
		items = {
			"Bandage", 10,
			"Bandaid", 10,
			"BeefJerky", 20,
			"CannedBolognese", 20,
			"CannedCarrots2", 20,
			"CannedChili", 20,
			"CannedCorn", 20,
			"CannedCornedBeef", 20,
			"CannedFruitCocktail", 20,
			"CannedMushroomSoup", 20,
			"CannedPeaches", 20,
			"CannedPeas", 20,
			"CannedPineapple", 20,
			"CannedPotato2", 20,
			"CannedSardines", 20,
			"CannedTomato2", 20,
			"Crisps", 20,
			"Crisps2", 20,
			"Crisps3", 20,
			"Crisps4", 20,
			"DoubleBarrelShotgun", 8,
			"FirstAidKit", 4,
			"LouisvilleMap1", 20,
			"LouisvilleMap2", 20,
			"LouisvilleMap3", 20,
			"LouisvilleMap4", 20,
			"LouisvilleMap5", 20,
			"LouisvilleMap6", 20,
			"LouisvilleMap7", 20,
			"LouisvilleMap8", 20,
			"LouisvilleMap9", 20,
			"Machete", 4,
			"MarchRidgeMap", 20,
			"MuldraughMap", 20,
			"RiversideMap", 20,
			"RosewoodMap", 20,
			"SewingKit", 2,
			"Shotgun", 10,
			"ShotgunShellsBox", 10,
			"TinnedBeans", 20,
			"TinnedSoup", 20,
			"WestpointMap", 20,
			"BrazilianFood.Fofura", 20,
		}
	}

	SuburbsDistributions.Bag_WorkerBag = {
		rolls = 1,
		items = {
			"BluePen", 8,
			"Chocolate", 8,
			"Cigarettes", 4,
			"Crisps", 10,
			"PeanutButterSandwich", 10,
			"Peanuts", 8,
			"Pen", 8,
			"Pencil", 10,
			"RedPen", 8,
			"RubberBand", 1,
			"Scissors", 2,
			"SunflowerSeeds", 8,
			"WaterBottleFull", 10,
			"BrazilianFood.Fofura", 10,
		}
	}

	SuburbsDistributions.GroceryBag4 = {
		rolls = 1,
		items = {
			"Aluminum", 50,
			"BakingSoda", 50,
			"Butter", 20,
			"ChocolateChips", 50,
			"ChocolateChips", 10,
			"CocoaPowder", 50,
			"CocoaPowder", 10,
			"Flour", 100,
			"Flour", 20,
			"Lard", 20,
			"Margarine", 20,
			"OatsRaw", 20,
			"OilOlive", 20,
			"OilVegetable", 20,
			"Sugar", 50,
			"Sugar", 10,
			"SugarBrown", 20,
			"Yeast", 20,
			"BrazilianFood.FarinhaTapioca", 100,
			"BrazilianFood.FarinhaTapioca", 20,
		}
	}


end
Events.OnPreDistributionMerge.Add(preDistributionMerge);